# apps/backend/Dockerfile.dev
FROM maven:3.9-eclipse-temurin-21

WORKDIR /workspace
EXPOSE 8080

RUN apt-get update && apt-get install -y --no-install-recommends curl && rm -rf /var/lib/apt/lists/*

# No COPY because ./apps/backend:/workspace in compose
CMD ["mvn","-DskipTests","spring-boot:run"]